version: "3.8"
services: 
  web:
    image: nginx:1.18-alpine
    ports: 
      - 8080:80
    volumes:
      - ./backend/src:/work
      - vendor:/work/vendor
      - php-fpm-socket:/var/run/php-fpm
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      app:
        ipv4_address: 192.168.0.10
     

  backend:
    build: ./backend
    volumes: 
      - ./backend/src:/work
      - vendor:/work/vendor
      - php-fpm-socket:/var/run/php-fpm

  frontend:
    build: ./frontend
    ports:
      - 8000:3000
      - 443:3000
    volumes:
      - ./frontend/src:/usr/src/app/project
      - node_modules:/usr/src/app/project/node_modules
    command: sh -c "cd project && yarn start"
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - HTTPS=true
    dns: 
      - 8.8.8.8
    networks: 
      app:
        ipv4_address: 192.168.0.20
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/data:/var/lib/mysql
    ports:
    - 3306:3306

volumes:
  php-fpm-socket:
  db-store:
  vendor:
  node_modules:

networks: 
  app:
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 192.168.0.0/16